package edu.wpi.cs.wpisuitetng.modules.taskmanager.view;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

/**
 * The class <code>SearchBarGroupTest</code> contains tests for the class {@link <code>SearchBarGroup</code>}
 *
 * @pattern JUnit Test Case
 * @generatedBy CodePro at 12/11/14 9:41 PM
 * @author dbogatov
 * @version $Revision$
 */
public class SearchBarGroupTest {

    /**
     * Checks whether the cancel button clears the test field and check boxes.
     */
    @Test
    public void cancelButtonTest() {
        SearchBarGroup sbg = new SearchBarGroup();
        sbg.setCheckBoxes(true, false, false, true);
        sbg.clickCancel();
        assertTrue(sbg.isReset());
    }
}

/*
 * $CPS$ This comment was generated by CodePro. Do not edit it. patternId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern strategyId =
 * com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase additionalTestNames =
 * assertTrue = false callTestMethod = true createMain = false createSetUp = false createTearDown =
 * false createTestFixture = false createTestStubs = false methods = package =
 * edu.wpi.cs.wpisuitetng.modules.taskmanager.view package.sourceFolder = TaskManager/src/test/java
 * superclassType = junit.framework.TestCase testCase = SearchBarGroupTest testClassType =
 * SearchBarGroup
 */
